Update instructions for creating a QuickLab and adding collaborators

diff --git a/.github/workflows/mirrorGuide.yml b/.github/workflows/mirrorGuide.yml
--- a/.github/workflows/mirrorGuide.yml
+++ b/.github/workflows/mirrorGuide.yml
@@ -1,4 +1,4 @@
-name: Mirror a guide to GitLab Repo
+name: Mirror a guide to AWB
 
 on:
   workflow_dispatch:
@@ -59,27 +59,49 @@ jobs:
         repo: ${{fromJson(needs.matrixProd.outputs.matrix)}}
     steps:
       - uses: actions/checkout@master
-      - name: Check Files
+      - name: Check If Guide Exists
         run: |
           if [ "${{ github.event.inputs.guide_name }}" = "${{matrix.repo.guide}}" ]; then 
-            echo "Mirroring "${{ github.event.inputs.guide_name }}" to "${{matrix.repo.gitlab}}"";
-            GITLAB="${{matrix.repo.gitlab}}" >> $GITHUB_ENV;
-            GITLAB_BRANCH="${{matrix.repo.gitlab-branch}}" >> $GITHUB_ENV;
+            echo "Mirroring "${{ github.event.inputs.guide_name }}" to AuthorWorkbench";
+            echo "awb url: https://author-workbench.skills.network/quicklabs/${{matrix.repo.quicklab_id}}/labs/${{matrix.repo.lab_id}}";
           else
-            echo "Skipping "${{matrix.repo.guide}}"";
+            echo "Skipping "${{matrix.repo.github}}"";
             exit 1;
           fi
 
-      - name: Mirror to Gitlab
-        uses: s0/git-publish-subdir-action@develop
+      - name: Check for insturctions.md
+        run: |
+          FILE_PATH="instructions/${{ matrix.repo.github }}/instructions.md"
+          if [[ -f "$FILE_PATH" ]]; then
+            echo "'$FILE_PATH' exists."
+          else
+            echo "'$FILE_PATH' does not exist."
+            exit 1
+          fi
+      - name: Mirror to AWB
         env:
-          REPO: git@ssh.author-gitlab.skills.network:quicklabs/${{matrix.repo.gitlab}}.git
-          BRANCH: ${{matrix.repo.gitlab-branch}}
-          FOLDER: instructions/${{matrix.repo.github}}
-          MESSAGE: "{msg}" # Sets the commit message on gitlab to be the same as on github.
-          SSH_PRIVATE_KEY: ${{secrets.DEPLOY_KEY_QUICK_LABS}}
-          KNOWN_HOSTS_FILE: .github/workflows/known_hosts # Needed if target repo is not on github.com.
-          SKIP_EMPTY_COMMITS: "true"
+          LAB_ID: ${{ matrix.repo.lab_id }}
+          OAUTH_TOKEN: ${{ secrets.AWB_OAUTH_TOKEN }}
+          CHANGE_LOG: "{{msg}}"
+          PUBLISH: true
+          FILE_PATH: instructions/${{ matrix.repo.github }}/instructions.md
+        run: |
+          response=$(curl -X POST "https://author.skills.network/api/v1/labs/${LAB_ID}/lab_versions/latest/drafts" \
+            -H "Authorization: Bearer ${OAUTH_TOKEN}" \
+            -F "file=@${FILE_PATH}" \
+            -F "draft[changelog]=${CHANGE_LOG}" \
+            -F "publish=${PUBLISH}" \
+            -w "%{http_code}" -o result.txt)
+  
+          cat result.txt
+          echo "Response Code: $response"
+  
+          if [[ "$response" -ne 200 && "$response" -ne 201 ]];
+            echo "Request failed with status $response"
+            exit 1  # Exit the script with error if not successful
+          else
+            echo "Request succeeded with status $response"
+          fi
 
   deployStaging:
     needs: [matrixStaging]
@@ -94,24 +116,45 @@ jobs:
       - uses: actions/checkout@master
         with: 
           ref: staging
-      - name: Check Files
+      - name: Check If Guide Exists
         run: |
           if [ "${{ github.event.inputs.guide_name }}" = "${{matrix.repo.guide}}" ]; then 
-            echo "Mirroring "${{ github.event.inputs.guide_name }}" to "${{matrix.repo.gitlab}}"";
-            GITLAB="${{matrix.repo.gitlab}}" >> $GITHUB_ENV;
-            GITLAB_BRANCH="${{matrix.repo.gitlab-branch}}" >> $GITHUB_ENV;
+            echo "Mirroring "${{ github.event.inputs.guide_name }}" to AuthorWorkbench";
+            echo "awb url: https://author-workbench.skills.network/quicklabs/${{matrix.repo.quicklab_id}}/labs/${{matrix.repo.lab_id}}";
           else
             echo "Skipping "${{matrix.repo.github}}"";
             exit 1;
           fi
-
-      - name: Mirror to Gitlab
-        uses: s0/git-publish-subdir-action@develop
+      - name: Check for insturctions.md
+        run: |
+          FILE_PATH="instructions/${{ matrix.repo.github }}/instructions.md"
+          if [[ -f "$FILE_PATH" ]]; then
+            echo "'$FILE_PATH' exists."
+          else
+            echo "'$FILE_PATH' does not exist."
+            exit 1
+          fi
+      - name: Mirror to AWB
         env:
-          REPO: git@ssh.author-gitlab.skills.network:quicklabs/${{matrix.repo.gitlab}}.git
-          BRANCH: ${{matrix.repo.gitlab-branch}}
-          FOLDER: instructions/${{matrix.repo.github}}
-          MESSAGE: "{msg}" # Sets the commit message on gitlab to be the same as on github.
-          SSH_PRIVATE_KEY: ${{secrets.DEPLOY_KEY_QUICK_LABS}}
-          KNOWN_HOSTS_FILE: .github/workflows/known_hosts # Needed if target repo is not on github.com.
-          SKIP_EMPTY_COMMITS: "true"
+          LAB_ID: ${{ matrix.repo.lab_id }}
+          OAUTH_TOKEN: ${{ secrets.AWB_OAUTH_TOKEN }}
+          CHANGE_LOG: "{{msg}}"
+          PUBLISH: false
+          FILE_PATH: instructions/${{ matrix.repo.github }}/instructions.md
+        run: |
+          response=$(curl -X POST "https://author.skills.network/api/v1/labs/${LAB_ID}/lab_versions/latest/drafts" \
+            -H "Authorization: Bearer ${OAUTH_TOKEN}" \
+            -F "file=@${FILE_PATH}" \
+            -F "draft[changelog]=${CHANGE_LOG}" \
+            -F "publish=${PUBLISH}" \
+            -w "%{http_code}" -o result.txt)
+  
+          cat result.txt
+          echo "Response Code: $response"
+  
+          if [[ "$response" -ne 200 && "$response" -ne 201 ]];
+            echo "Request failed with status $response"
+            exit 1  # Exit the script with error if not successful
+          else
+            echo "Request succeeded with status $response"
+          fi
